/*
👉 Question for you: do you want to keep copying the stores folder from Aileean into NaughtSea every time, or would you rather share one single datastore between both projects (so changes in one automatically show up in the other)? I can show you how to set up a shared alias in vite.config.ts so you don’t need to copy things around.
*/

// src/stores/counter.ts
import { defineStore } from 'pinia'

export const useOrSomethingStore = defineStore('or_something', {
  state: () => ({
/*
    count: 0,
    links: [
      { name: 'Home', url: '/' },
      { name: 'About', url: '/about' },
    ],
  }),
  actions: {
    increment() {
      this.count++
    }
  }
})
*/


    arrows: [
      /*
#00003d for ⇦
*/
      {
        'hsl °': 240,
        '': '',
        pngs: 'keyboard_arrow_left.png',
        unicode: '⇦',
        'material icon': 'keyboard_arrow_left',
        username: 'growinggenkiness@gmail.com',
        hsl: 'hsl(240.0, 100.0%, 81.0%)',
        hex: '#9e9eff',
        ok: 'oklch(74.2% 0.086 245.8)',
        w3: '--',
        'button name': 'LEFT',
        'short name': 'LEFT',
        url: 'file:///D:/125/TailWinds/gg-LEFT.html',
        target: '_blank'   // 👈 add this
      },
      /*
#444444 for ⇩
*/

      {
        'hsl °': 341.7,
        '': '',
        pngs: 'keyboard_arrow_down.png',
        unicode: '⇩',
        'material icon': 'keyboard_arrow_down',
        username: 'veronica.cindyskids@gmail.com',
        hsl: 'hsl(341.7, 28.4%, 15.9%)',
        hex: '#341d24',
        ok: 'oklch(26.4% 0.036 6.0)',
        w3: '--',
        'button name': 'DOWN',
        'short name': 'DOWN',
        url: 'file:///D:/125/TailWinds/gg-DOWN.html',
      },
      {
        'hsl °': 342.4,
        '': '',
        pngs: 'graph_5.png',
        unicode: '🌀',
        'material icon': 'Graph_5',
        username: 'veronicajeananderson@outlook.com',
        hsl: 'hsl(342.4, 12.8%, 26.1%)',
        hex: '#4b3a3f',
        ok: 'oklch(37.0% 0.029 9.8)',
        w3: '--',
        'button name': 'CENTER',
        'short name': 'CENTER',
        url: 'file:///D:/125/TailWinds/gg-CENTER.html',
      },
      /* #bbbbbb for ⇧ */
      {
        'hsl °': 341.5,
        '': '',
        pngs: 'keyboard_arrow_up.png',
        unicode: '⇧',
        'material icon': 'keyboard_arrow_up',
        username: 'mom.veronica@gmail.com',
        hsl: 'hsl(341.5, 28.3%, 36.1%)',
        hex: '#764252',
        ok: 'oklch(44.8% 0.070 5.5)',
        w3: '--',
        'button name': 'UP',
        'short name': 'UP',
        url: 'file:///D:/125/TailWinds/gg-UP.html',
      },
      /* #3d0000 for ⇨ */

      {
        'hsl °': 356.8,
        '': '',
        pngs: 'keyboard_arrow_right.png',
        unicode: '⇨',
        'material icon': 'keyboard_arrow_right',
        username: 'theyeariturnedfifty@outlook.com',
        hsl: 'hsl(356.8, 100.0%, 74.1%)',
        hex: '#ff7b82',
        ok: 'oklch(73.9% 0.163 14.3)',
        w3: '--',
        'button name': 'RIGHT',
        'short name': 'RIGHT',
        url: 'file:///D:/125/TailWinds/gg-RIGHT.html',
      },
    ],
    things: [
      {
        'hsl °': 42.9,
        '': '',
        pngs: 'width_normal.png',
        unicode: '📐',
        'material icon': 'width_normal',
        username: 'veronicajinthe@gmail.com',
        hsl: 'hsl(42.9, 74.4%, 49.0%)',
        hex: '#DAA520',
        ok: 'oklch(75.2% 0.129 46.2)',
        w3: 'Goldenrod',
        'button name': 'frame.html',
        'short name': '今',
        url: 'href="file:///D:/125/Tailwinds/frame.html',
      },
      {
        'hsl °': 27.6,
        '': '',
        pngs: 'widget_width.png',
        unicode: '🐮',
        'material icon': 'widget_width',
        username: 'purpleprojectspdx97123@gmail.com',
        hsl: 'hsl(27.6, 87.1%, 66.7%)',
        hex: '#F4A460',
        ok: 'oklch(78.5% 0.136 33.2)',
        w3: 'sandybrown',
        'button name': 'calf',
        'short name': 'calf',
        url: 'http://localhost:5174/',
      },
      {
        'hsl °': 16.2,
        '': '',
        pngs: 'heat.png',
        unicode: '🌶️',
        'material icon': 'heat',
        username: 'jeanieandie@gmail.com',
        hsl: 'hsl(16.2, 100.0%, 50.0%)',
        hex: '#FF4500',
        ok: 'oklch(66.0% 0.227 20.8)',
        w3: 'orangered',
        'button name': '',
        'short name': '',
        url: '',
      },
      {
        'hsl °': 349.5,
        '': '',
        pngs: 'token.png',
        unicode: '🩰',
        'material icon': 'token',
        username: 'gdkp.org@gmail.com',
        hsl: 'hsl(349.5, 100.0%, 87.6%)',
        hex: '#FFC0CB',
        ok: 'oklch(87.0% 0.085 12.2)',
        w3: 'pink',
        'button name': 'calf/BWGP',
        'short name': 'bwgp',
        url: 'http://localhost:5174/BWGP',
      },

      {
        'hsl °': 342.2,
        '': '',
        pngs: 'wine_bar.png',
        unicode: '🍷',
        'material icon': 'wine_bar',
        username: 'allostasissy@gmail.com',
        hsl: 'hsl(342.2, 27.8%, 26.1%)',
        hex: '#55303b',
        ok: 'oklch(36.0% 0.053 6.0)',
        w3: '--',
        'button name': 'give_me_spice',
        'short name': 'allostasissy',
        url: 'file:///D:/125/TailWinds/give_me_spice.html',
      },
      {
        'hsl °': 276.87,
        '': '',
        pngs: 'visibility.png',
        unicode: '🧿',
        'material icon': 'visibility',
        username: 'a020f0ff@gmail.com',
        hsl: 'hsl(276,87%,53%)',
        hex: '#a020f0',
        ok: 'oklch(56.02% 0.276 306.71)',
        w3: '--',
        'button name': '',
        'short name': '',
        url: '',
      },

      {
        'hsl °': 218.5,
        '': '',
        pngs: 'patient_list.png',
        unicode: '🧙‍♂️',
        'material icon': 'patient_list',
        username: 'meleneth@gmail.com',
        hsl: 'hsl(219, 79%, 66%)',
        hex: '#6495ED',
        ok: 'oklch(65.1% 0.188 264.0)',
        w3: 'CornflowerBlue',
        'button name': 'twitch/Meleneth',
        'short name': 'mel',
        url: 'https://www.twitch.tv/meleneth',
      },
      {
        'hsl °': 203,
        '': '',
        pngs: 'replay_5.png',
        unicode: '🕵️‍♀️',
        'material icon': 'replay_5',
        username: 'docventur@gmail.com',
        hsl: 'hsl(203.0, 92.0%, 75.5%)',
        hex: '#87CEFA',
        ok: 'oklch(82.4% 0.070 213.2)',
        w3: 'lightskyblue',
        'button name': 'calf/tyit50',
        'short name': 'tyit50',
        url: 'http://localhost:5173/TYIT50vue',
      },
      {
        'hsl °': 195.1,
        '': '',
        pngs: 'category_search.png',
        unicode: '⛵',
        'material icon': 'category_search',
        username: 'oregongyre@gmail.com',
        hsl: 'hsl(195.1, 100.0%, 50.0%)',
        hex: '#00BFFF',
        ok: 'oklch(75.9% 0.139 209.0)',
        w3: 'DeepSkyBlue',
        'button name': 'NaughtSea',
        'short name': '∅©',
        url: 'http://localhost:5173/',
      },
      {
        'hsl °': 159.6,
        '': '',
        pngs: 'navigation.png',
        unicode: '🔰',
        'material icon': 'navigation',
        username: 'veronicajinthenazarene@gmail.com',
        hsl: 'hsl(159.6, 50.7%, 60.2%)',
        hex: '#66CDAA',
        ok: 'oklch(78.0% 0.055 152.8)',
        w3: 'mediumaquamarine',
        'button name': 'material-symbols-outlined',
        'short name': 'icons',
        url: 'href="file:///D:/125/Tailwinds/frame.html',
      },
      {
        'hsl °': 90,
        '': '',
        pngs: 'cycle.png',
        unicode: '👩‍💻',
        'material icon': 'cycle',
        username: 'eonsofdung@gmail.com',
        hsl: 'hsl(90, 100.0%, 50.0%)',
        hex: '#7FFF00',
        ok: 'oklch(87.82% 0.258 134.39)',
        w3: 'Chartreuse',
        'button name': 'vueJeanie',
        'short name': 'vue人',
        url: 'href="http://localhost:5175/',
      },

    ],
  }),
})
