
<template>
  <div>
  <nav  class="flex flex-wrap items-center justify-center gap-3 p-10">
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/">&nbsp;| 🥰∅ NaughtSea |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/orientation">&nbsp;|  📐 Orientation |&nbsp;</RouterLink>      
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/anchor">&nbsp;|  🛠 Git |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/dailies">&nbsp;|  🎬 Dailies |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/royalwe">&nbsp;|  👑 RoyalWe |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/">&nbsp;| 📆 monthlies |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/forecastle">&nbsp;| 📊 Forecasting |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/">&nbsp;| 📅 Yearlies |&nbsp;</RouterLink>  
    <a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" target="_blank" rel="noopener noreferrer">| 👌 Perfection |</a>          
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/">&nbsp;| 📓 ㏒ |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/library">&nbsp;| 🏛️ libraries |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/">&nbsp;| 💬 gG |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/exhibits">&nbsp;| 🎪 Xhibition |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/">&nbsp;| 📁 Sorting |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/vocabulary">&nbsp;| 📖 Vocabulary |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/check">&nbsp;| ✅ Czech |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/royalwethepeople">&nbsp;| 🗽 RoyalWeThePeople |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/amberVue"> | 🛕 amberVue |</RouterLink>       
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/blueVue"> | 🛹 blueVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/cyanVue"> | 🔰 cyanVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/emeraldVue"> | 🦎 emeraldVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/fuchsiaVue"> | 🧠 fuchsiaVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/grayVue"> | 🧷 grayVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/greenVue"> | 💲 greenVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/indigoVue"> | 🎵 indigoVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/limeVue"> | 🦗 limeVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/neutralVue"> | 📺 neutralVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/orangeVue"> | 🏀 orangeVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/pinkVue"> | 🐷 pinkVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/purpleVue"> | 🛍️ purpleVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/redVue"> | 🛑 redVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/roseVue"> | 🌹 roseVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/skyVue"> | 🌃 skyVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/slateVue"> | 🐃 slateVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/stoneVue"> | 🧱 stoneVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/tealVue"> | 🧩 tealVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/violetVue"> | ☔ violetVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/yellowVue"> | ⚜️ yellowVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/zincVue"> | 🛒 zincVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/PrimaryVue"> | 🛒 Primary |</RouterLink>  
    </nav> 


  <nav  class="flex flex-wrap items-center justify-center gap-3 p-10">
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/">&nbsp;| 🥰∅ NaughtSea |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/orientation">&nbsp;|  📐 Orientation |&nbsp;</RouterLink>      
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/anchor">&nbsp;|  🛠 Git |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/dailies">&nbsp;|  🎬 Dailies |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/royalwe">&nbsp;|  👑 RoyalWe |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/">&nbsp;| 📆 monthlies |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/forecastle">&nbsp;| 📊 Forecasting |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/">&nbsp;| 📅 Yearlies |&nbsp;</RouterLink>  
    <a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" target="_blank" rel="noopener noreferrer">| 👌 Perfection |</a>          
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/">&nbsp;| 📓 ㏒ |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/library">&nbsp;| 🏛️ libraries |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/">&nbsp;| 💬 gG |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/exhibits">&nbsp;| 🎪 Xhibition |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/">&nbsp;| 📁 Sorting |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/vocabulary">&nbsp;| 📖 Vocabulary |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/check">&nbsp;| ✅ Czech |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/royalwethepeople">&nbsp;| 🗽 RoyalWeThePeople |&nbsp;</RouterLink>            
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/amberVue"> | 🛕 amberVue |</RouterLink>       
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/blueVue"> | 🛹 blueVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/cyanVue"> | 🔰 cyanVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/emeraldVue"> | 🦎 emeraldVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/fuchsiaVue"> | 🧠 fuchsiaVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/grayVue"> | 🧷 grayVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/greenVue"> | 💲 greenVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/indigoVue"> | 🎵 indigoVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/limeVue"> | 🦗 limeVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/neutralVue"> | 📺 neutralVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/orangeVue"> | 🏀 orangeVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/pinkVue"> | 🐷 pinkVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/purpleVue"> | 🛍️ purpleVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/redVue"> | 🛑 redVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/roseVue"> | 🌹 roseVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/skyVue"> | 🌃 skyVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/slateVue"> | 🐃 slateVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/stoneVue"> | 🧱 stoneVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/tealVue"> | 🧩 tealVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/violetVue"> | ☔ violetVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/yellowVue"> | ⚜️ yellowVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/zincVue"> | 🛒 zincVue |</RouterLink>  
    <RouterLink class="p-2.5; text-sky-500 hover:text-yellow-200 border border-sky-500 cursor-pointer" 
    to="/PrimaryVue"> | 🛒 Primary |</RouterLink>  
    </nav> 
  </div>

</template>
