<script setup lang="ts">
defineOptions({
  name: "yearsBar"
});
</script>
<template>
<div class="grid grid-cols-[repeat(51,minmax(0,1fr))] w-full h-6 gap-1 p-2">
  <div class="bg-[hsl(0,0%,0%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">75</a></div>
  <div class="bg-[hsl(0,0%,2%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">76</a></div>
  <div class="bg-[hsl(0,0%,4%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">77</a></div>
  <div class="bg-[hsl(0,0%,6%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">78</a></div>
  <div class="bg-[hsl(0,0%,8%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">79</a></div>
  <div class="bg-[hsl(0,0%,10%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">80</a></div>
  <div class="bg-[hsl(0,0%,12%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">81</a></div>
  <div class="bg-[hsl(0,0%,14%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">82</a></div>
  <div class="bg-[hsl(0,0%,16%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">83</a></div>
  <div class="bg-[hsl(0,0%,18%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">84</a></div>
  <div class="bg-[hsl(0,0%,20%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">85</a></div>
  <div class="bg-[hsl(0,0%,22%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">86</a></div>
  <div class="bg-[hsl(0,0%,24%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">87</a></div>
  <div class="bg-[hsl(0,0%,26%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">88</a></div>
  <div class="bg-[hsl(0,0%,28%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">89</a></div>
  <div class="bg-[hsl(0,0%,30%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">90</a></div>
  <div class="bg-[hsl(0,0%,32%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">91</a></div>
  <div class="bg-[hsl(0,0%,34%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">92</a></div>
  <div class="bg-[hsl(0,0%,36%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">93</a></div>
  <div class="bg-[hsl(0,0%,38%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">94</a></div>
  <div class="bg-[hsl(0,0%,40%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">95</a></div>
  <div class="bg-[hsl(0,0%,42%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">96</a></div>
  <div class="bg-[hsl(0,0%,44%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">97</a></div>
  <div class="bg-[hsl(0,0%,46%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">98</a></div>
  <div class="bg-[hsl(0,0%,48%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=rblt2EtFfC4" class="block w-full h-full" target="_blank" rel="noopener noreferrer">99</a></div>

  <div class="bg-[hsl(0,0%,50%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">100</a></div>
  <div class="bg-[hsl(0,0%,50%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">101</a></div>
  <div class="bg-[hsl(0,0%,52%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">102</a></div>
  <div class="bg-[hsl(0,0%,54%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">103</a></div>
  <div class="bg-[hsl(0,0%,56%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">104</a></div>
  <div class="bg-[hsl(0,0%,58%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">105</a></div>
  <div class="bg-[hsl(0,0%,60%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">106</a></div>
  <div class="bg-[hsl(0,0%,62%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">107</a></div>
  <div class="bg-[hsl(0,0%,64%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">108</a></div>
  <div class="bg-[hsl(0,0%,68%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">109</a></div>
  <div class="bg-[hsl(0,0%,70%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">110</a></div>
  <div class="bg-[hsl(0,0%,72%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">111</a></div>
  <div class="bg-[hsl(0,0%,74%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">112</a></div>
  <div class="bg-[hsl(0,0%,76%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">113</a></div>
  <div class="bg-[hsl(0,0%,78%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">114</a></div>
  <div class="bg-[hsl(0,0%,80%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">115</a></div>
  <div class="bg-[hsl(0,0%,82%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">116</a></div>
  <div class="bg-[hsl(0,0%,84%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">117</a></div>
  <div class="bg-[hsl(0,0%,86%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">118</a></div>
  <div class="bg-[hsl(0,0%,88%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">119</a></div>
  <div class="bg-[hsl(0,0%,90%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">120</a></div>
  <div class="bg-[hsl(0,0%,92%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">121</a></div>
  <div class="bg-[hsl(0,0%,94%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">122</a></div>
  <div class="bg-[hsl(0,0%,96%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">123</a></div>
  <div class="bg-[hsl(0,0%,98%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">124</a></div>
  <div class="bg-[hsl(0,0%,100%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">125</a></div>
</div>
<div class="grid grid-cols-[repeat(51,minmax(0,1fr))] w-full h-6 gap-2 p-4">
  <div class="bg-[hsl(0,0%,0%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">75</a></div>
  <div class="bg-[hsl(0,0%,2%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">76</a></div>
  <div class="bg-[hsl(0,0%,4%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">77</a></div>
  <div class="bg-[hsl(0,0%,6%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">78</a></div>
  <div class="bg-[hsl(0,0%,8%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">79</a></div>
  <div class="bg-[hsl(0,0%,10%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">80</a></div>
  <div class="bg-[hsl(0,0%,12%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">81</a></div>
  <div class="bg-[hsl(0,0%,14%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">82</a></div>
  <div class="bg-[hsl(0,0%,16%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">83</a></div>
  <div class="bg-[hsl(0,0%,18%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">84</a></div>
  <div class="bg-[hsl(0,0%,20%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">85</a></div>
  <div class="bg-[hsl(0,0%,22%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">86</a></div>
  <div class="bg-[hsl(0,0%,24%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">87</a></div>
  <div class="bg-[hsl(0,0%,26%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">88</a></div>
  <div class="bg-[hsl(0,0%,28%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">89</a></div>
  <div class="bg-[hsl(0,0%,30%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">90</a></div>
  <div class="bg-[hsl(0,0%,32%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">91</a></div>
  <div class="bg-[hsl(0,0%,34%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">92</a></div>
  <div class="bg-[hsl(0,0%,36%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">93</a></div>
  <div class="bg-[hsl(0,0%,38%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">94</a></div>
  <div class="bg-[hsl(0,0%,40%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">95</a></div>
  <div class="bg-[hsl(0,0%,42%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">96</a></div>
  <div class="bg-[hsl(0,0%,44%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">97</a></div>
  <div class="bg-[hsl(0,0%,46%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">98</a></div>
  <div class="bg-[hsl(0,0%,48%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=rblt2EtFfC4" class="block w-full h-full" target="_blank" rel="noopener noreferrer">99</a></div>

  <div class="bg-[hsl(0,0%,50%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">0</a></div>
  <div class="bg-[hsl(0,0%,50%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">1</a></div>
  <div class="bg-[hsl(0,0%,52%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">2</a></div>
  <div class="bg-[hsl(0,0%,54%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">3</a></div>
  <div class="bg-[hsl(0,0%,56%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">4</a></div>
  <div class="bg-[hsl(0,0%,58%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">5</a></div>
  <div class="bg-[hsl(0,0%,60%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">6</a></div>
  <div class="bg-[hsl(0,0%,62%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">7</a></div>
  <div class="bg-[hsl(0,0%,64%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">8</a></div>
  <div class="bg-[hsl(0,0%,68%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">9</a></div>
  <div class="bg-[hsl(0,0%,70%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">10</a></div>
  <div class="bg-[hsl(0,0%,72%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">11</a></div>
  <div class="bg-[hsl(0,0%,74%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">12</a></div>
  <div class="bg-[hsl(0,0%,76%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">13</a></div>
  <div class="bg-[hsl(0,0%,78%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">14</a></div>
  <div class="bg-[hsl(0,0%,80%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">15</a></div>
  <div class="bg-[hsl(0,0%,82%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">16</a></div>
  <div class="bg-[hsl(0,0%,84%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">17</a></div>
  <div class="bg-[hsl(0,0%,86%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">18</a></div>
  <div class="bg-[hsl(0,0%,88%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">19</a></div>
  <div class="bg-[hsl(0,0%,90%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">20</a></div>
  <div class="bg-[hsl(0,0%,92%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">21</a></div>
  <div class="bg-[hsl(0,0%,94%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">22</a></div>
  <div class="bg-[hsl(0,0%,96%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">23</a></div>
  <div class="bg-[hsl(0,0%,98%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">24</a></div>
  <div class="bg-[hsl(0,0%,100%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">25</a></div>
</div>

</template>
