<script setup lang="ts">
defineOptions({
  name: "yearsBar"
});
</script>
<template>
<!--
<div class="grid grid-cols-[repeat(51,minmax(0,1fr))] w-full h-6 gap-2 p-4 hubot-sans  text-[22px]">
  <div class="bg-[hsl(0,0%,0%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">75</a></div>
  <div class="bg-[hsl(0,0%,2%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">76</a></div>
  <div class="bg-[hsl(0,0%,4%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">77</a></div>
  <div class="bg-[hsl(0,0%,6%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">78</a></div>
  <div class="bg-[hsl(0,0%,8%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">79</a></div>
  <div class="bg-[hsl(0,0%,10%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">80</a></div>
  <div class="bg-[hsl(0,0%,12%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">81</a></div>
  <div class="bg-[hsl(0,0%,14%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">82</a></div>
  <div class="bg-[hsl(0,0%,16%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">83</a></div>
  <div class="bg-[hsl(0,0%,18%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">84</a></div>
  <div class="bg-[hsl(0,0%,20%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">85</a></div>
  <div class="bg-[hsl(0,0%,22%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">86</a></div>
  <div class="bg-[hsl(0,0%,24%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">87</a></div>
  <div class="bg-[hsl(0,0%,26%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">88</a></div>
  <div class="bg-[hsl(0,0%,28%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">89</a></div>
  <div class="bg-[hsl(0,0%,30%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">90</a></div>
  <div class="bg-[hsl(0,0%,32%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">91</a></div>
  <div class="bg-[hsl(0,0%,34%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">92</a></div>
  <div class="bg-[hsl(0,0%,36%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">93</a></div>
  <div class="bg-[hsl(0,0%,38%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">94</a></div>
  <div class="bg-[hsl(0,0%,40%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">95</a></div>
  <div class="bg-[hsl(0,0%,42%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">96</a></div>
  <div class="bg-[hsl(0,0%,44%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">97</a></div>
  <div class="bg-[hsl(0,0%,46%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">98</a></div>
  <div class="bg-[hsl(0,0%,48%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=rblt2EtFfC4" class="block w-full h-full" target="_blank" rel="noopener noreferrer">99</a></div>

  <div class="bg-[hsl(0,0%,50%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">0</a></div>
  <div class="bg-[hsl(0,0%,50%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">1</a></div>
  <div class="bg-[hsl(0,0%,52%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">2</a></div>
  <div class="bg-[hsl(0,0%,54%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">3</a></div>
  <div class="bg-[hsl(0,0%,56%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">4</a></div>
  <div class="bg-[hsl(0,0%,58%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">5</a></div>
  <div class="bg-[hsl(0,0%,60%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">6</a></div>
  <div class="bg-[hsl(0,0%,62%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">7</a></div>
  <div class="bg-[hsl(0,0%,64%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">8</a></div>
  <div class="bg-[hsl(0,0%,68%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">9</a></div>
  <div class="bg-[hsl(0,0%,70%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">10</a></div>
  <div class="bg-[hsl(0,0%,72%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">11</a></div>
  <div class="bg-[hsl(0,0%,74%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">12</a></div>
  <div class="bg-[hsl(0,0%,76%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">13</a></div>
  <div class="bg-[hsl(0,0%,78%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">14</a></div>
  <div class="bg-[hsl(0,0%,80%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">15</a></div>
  <div class="bg-[hsl(0,0%,82%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">16</a></div>
  <div class="bg-[hsl(0,0%,84%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">17</a></div>
  <div class="bg-[hsl(0,0%,86%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">18</a></div>
  <div class="bg-[hsl(0,0%,88%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">19</a></div>
  <div class="bg-[hsl(0,0%,90%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">20</a></div>
  <div class="bg-[hsl(0,0%,92%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">21</a></div>
  <div class="bg-[hsl(0,0%,94%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">22</a></div>
  <div class="bg-[hsl(0,0%,96%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">23</a></div>
  <div class="bg-[hsl(0,0%,98%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">24</a></div>
  <div class="bg-[hsl(0,0%,100%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">25</a></div>
</div>
-->
<div class="grid grid-cols-[repeat(51,minmax(0,1fr))] w-full h-6 hubot-sans text-[33px] gap-1 p-1">
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⓪</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">①</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">②</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">③</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">④</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑤</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑥</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑦</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑧</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑨</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑩</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑪</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑫</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑬</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑭</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑮</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑯</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑰</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑱</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑲</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑳</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉑</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉒</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉓</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉔</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉕</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉖</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉗</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉘</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉙</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉚</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉛</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉜</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉝</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉞</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉟</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊱</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊲</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊳</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊴</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊵</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊶</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊷</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊸</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊹</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊺</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊻</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊼</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊽</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊾</a></div>
  <div class="cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊿</a></div>
</div>
<br>
<div class="grid grid-cols-[repeat(51,minmax(0,1fr))] w-full h-6 gap-2 p-2 hubot-sans text-[18px]">
  <div class="border border-[hsl(0,0%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center " ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">75</a></div>
  <div class="border border-[hsl(0,0%,2%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">76</a></div>
  <div class="border border-[hsl(0,0%,4%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">77</a></div>
  <div class="border border-[hsl(0,0%,6%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">78</a></div>
  <div class="border border-[hsl(0,0%,8%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">79</a></div>
  <div class="border border-[hsl(0,0%,10%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">80</a></div>
  <div class="border border-[hsl(0,0%,12%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">81</a></div>
  <div class="border border-[hsl(0,0%,14%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">82</a></div>
  <div class="border border-[hsl(0,0%,16%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">83</a></div>
  <div class="border border-[hsl(0,0%,18%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">84</a></div>
  <div class="border border-[hsl(0,0%,20%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">85</a></div>
  <div class="border border-[hsl(0,0%,22%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">86</a></div>
  <div class="border border-[hsl(0,0%,24%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">87</a></div>
  <div class="border border-[hsl(0,0%,26%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">88</a></div>
  <div class="border border-[hsl(0,0%,28%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">89</a></div>
  <div class="border border-[hsl(0,0%,30%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">90</a></div>
  <div class="border border-[hsl(0,0%,32%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">91</a></div>
  <div class="border border-[hsl(0,0%,34%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">92</a></div>
  <div class="border border-[hsl(0,0%,36%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">93</a></div>
  <div class="border border-[hsl(0,0%,38%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">94</a></div>
  <div class="border border-[hsl(0,0%,40%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">95</a></div>
  <div class="border border-[hsl(0,0%,42%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">96</a></div>
  <div class="border border-[hsl(0,0%,44%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">97</a></div>
  <div class="border border-[hsl(0,0%,46%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">98</a></div>
  <div class="border border-[hsl(0,0%,48%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=rblt2EtFfC4" class="block w-full h-full" target="_blank" rel="noopener noreferrer">99</a></div>

  <div class="border border-[hsl(0,0%,50%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">100</a></div>
  <div class="border border-[hsl(0,0%,50%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">101</a></div>
  <div class="border border-[hsl(0,0%,52%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">102</a></div>
  <div class="border border-[hsl(0,0%,54%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">103</a></div>
  <div class="border border-[hsl(0,0%,56%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">104</a></div>
  <div class="border border-[hsl(0,0%,58%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">105</a></div>
  <div class="border border-[hsl(0,0%,60%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">106</a></div>
  <div class="border border-[hsl(0,0%,62%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">107</a></div>
  <div class="border border-[hsl(0,0%,64%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">108</a></div>
  <div class="border border-[hsl(0,0%,68%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">109</a></div>
  <div class="border border-[hsl(0,0%,70%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">110</a></div>
  <div class="border border-[hsl(0,0%,72%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">111</a></div>
  <div class="border border-[hsl(0,0%,74%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">112</a></div>
  <div class="border border-[hsl(0,0%,76%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">113</a></div>
  <div class="border border-[hsl(0,0%,78%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">114</a></div>
  <div class="border border-[hsl(0,0%,80%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">115</a></div>
  <div class="border border-[hsl(0,0%,82%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">116</a></div>
  <div class="border border-[hsl(0,0%,84%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">117</a></div>
  <div class="border border-[hsl(0,0%,86%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">118</a></div>
  <div class="border border-[hsl(0,0%,88%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">119</a></div>
  <div class="border border-[hsl(0,0%,90%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">120</a></div>
  <div class="border border-[hsl(0,0%,92%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">121</a></div>
  <div class="border border-[hsl(0,0%,94%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">122</a></div>
  <div class="border border-[hsl(0,0%,96%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">123</a></div>
  <div class="border border-[hsl(0,0%,98%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">124</a></div>
  <div class="border border-[hsl(0,0%,100%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">125</a></div>
</div>


<!--
<div class="grid grid-cols-[repeat(51,minmax(0,1fr))] w-full h-6 gap-4 p-2 hubot-sans text-[18px]">
  <div class="bg-[hsl(0,0%,0%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center " ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">75</a></div>
  <div class="bg-[hsl(0,0%,2%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">76</a></div>
  <div class="bg-[hsl(0,0%,4%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">77</a></div>
  <div class="bg-[hsl(0,0%,6%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">78</a></div>
  <div class="bg-[hsl(0,0%,8%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">79</a></div>
  <div class="bg-[hsl(0,0%,10%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">80</a></div>
  <div class="bg-[hsl(0,0%,12%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">81</a></div>
  <div class="bg-[hsl(0,0%,14%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">82</a></div>
  <div class="bg-[hsl(0,0%,16%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">83</a></div>
  <div class="bg-[hsl(0,0%,18%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">84</a></div>
  <div class="bg-[hsl(0,0%,20%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">85</a></div>
  <div class="bg-[hsl(0,0%,22%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">86</a></div>
  <div class="bg-[hsl(0,0%,24%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">87</a></div>
  <div class="bg-[hsl(0,0%,26%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">88</a></div>
  <div class="bg-[hsl(0,0%,28%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">89</a></div>
  <div class="bg-[hsl(0,0%,30%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">90</a></div>
  <div class="bg-[hsl(0,0%,32%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">91</a></div>
  <div class="bg-[hsl(0,0%,34%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">92</a></div>
  <div class="bg-[hsl(0,0%,36%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">93</a></div>
  <div class="bg-[hsl(0,0%,38%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">94</a></div>
  <div class="bg-[hsl(0,0%,40%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">95</a></div>
  <div class="bg-[hsl(0,0%,42%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">96</a></div>
  <div class="bg-[hsl(0,0%,44%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">97</a></div>
  <div class="bg-[hsl(0,0%,46%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">98</a></div>
  <div class="bg-[hsl(0,0%,48%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=rblt2EtFfC4" class="block w-full h-full" target="_blank" rel="noopener noreferrer">99</a></div>

  <div class="bg-[hsl(0,0%,50%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">100</a></div>
  <div class="bg-[hsl(0,0%,50%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">101</a></div>
  <div class="bg-[hsl(0,0%,52%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">102</a></div>
  <div class="bg-[hsl(0,0%,54%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">103</a></div>
  <div class="bg-[hsl(0,0%,56%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">104</a></div>
  <div class="bg-[hsl(0,0%,58%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">105</a></div>
  <div class="bg-[hsl(0,0%,60%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">106</a></div>
  <div class="bg-[hsl(0,0%,62%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">107</a></div>
  <div class="bg-[hsl(0,0%,64%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">108</a></div>
  <div class="bg-[hsl(0,0%,68%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">109</a></div>
  <div class="bg-[hsl(0,0%,70%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">110</a></div>
  <div class="bg-[hsl(0,0%,72%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">111</a></div>
  <div class="bg-[hsl(0,0%,74%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">112</a></div>
  <div class="bg-[hsl(0,0%,76%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">113</a></div>
  <div class="bg-[hsl(0,0%,78%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">114</a></div>
  <div class="bg-[hsl(0,0%,80%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">115</a></div>
  <div class="bg-[hsl(0,0%,82%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">116</a></div>
  <div class="bg-[hsl(0,0%,84%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">117</a></div>
  <div class="bg-[hsl(0,0%,86%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">118</a></div>
  <div class="bg-[hsl(0,0%,88%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">119</a></div>
  <div class="bg-[hsl(0,0%,90%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">120</a></div>
  <div class="bg-[hsl(0,0%,92%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">121</a></div>
  <div class="bg-[hsl(0,0%,94%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">122</a></div>
  <div class="bg-[hsl(0,0%,96%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">123</a></div>
  <div class="bg-[hsl(0,0%,98%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">124</a></div>
  <div class="bg-[hsl(0,0%,100%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">125</a></div>
</div>

-->
<!--
<div class="grid grid-cols-[repeat(51,minmax(0,1fr))] w-full h-6 hubot-sans text-[33px] gap-1 p-1">
  <div class="border border-[hsl(0,0%,100%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⓪</a></div>
  <div class="border border-[hsl(0,0%,98%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">①</a></div>
  <div class="border border-[hsl(0,0%,96%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">②</a></div>
  <div class="border border-[hsl(0,0%,94%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">③</a></div>
  <div class="border border-[hsl(0,0%,92%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">④</a></div>
  <div class="border border-[hsl(0,0%,90%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑤</a></div>
  <div class="border border-[hsl(0,0%,88%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑥</a></div>
  <div class="border border-[hsl(0,0%,86%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑦</a></div>
  <div class="border border-[hsl(0,0%,84%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑧</a></div>
  <div class="border border-[hsl(0,0%,82%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑨</a></div>
  <div class="border border-[hsl(0,0%,80%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑩</a></div>
  <div class="border border-[hsl(0,0%,78%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑪</a></div>
  <div class="border border-[hsl(0,0%,76%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑫</a></div>
  <div class="border border-[hsl(0,0%,74%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑬</a></div>
  <div class="border border-[hsl(0,0%,72%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑭</a></div>
  <div class="border border-[hsl(0,0%,70%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑮</a></div>
  <div class="border border-[hsl(0,0%,68%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑯</a></div>
  <div class="border border-[hsl(0,0%,66%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑰</a></div>
  <div class="border border-[hsl(0,0%,64%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑱</a></div>
  <div class="border border-[hsl(0,0%,62%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑲</a></div>
  <div class="border border-[hsl(0,0%,60%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">⑳</a></div>
  <div class="border border-[hsl(0,0%,58%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉑</a></div>
  <div class="border border-[hsl(0,0%,56%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉒</a></div>
  <div class="border border-[hsl(0,0%,54%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉓</a></div>
  <div class="border border-[hsl(0,0%,52%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉔</a></div>
  <div class="border border-[hsl(0,0%,50%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉕</a></div>
  <div class="border border-[hsl(0,0%,48%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉖</a></div>
  <div class="border border-[hsl(0,0%,46%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉗</a></div>
  <div class="border border-[hsl(0,0%,44%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉘</a></div>
  <div class="border border-[hsl(0,0%,42%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉙</a></div>
  <div class="border border-[hsl(0,0%,40%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉚</a></div>
  <div class="border border-[hsl(0,0%,38%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉛</a></div>
  <div class="border border-[hsl(0,0%,36%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉜</a></div>
  <div class="border border-[hsl(0,0%,34%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉝</a></div>
  <div class="border border-[hsl(0,0%,32%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉞</a></div>
  <div class="border border-[hsl(0,0%,30%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㉟</a></div>
  <div class="border border-[hsl(0,0%,28%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊱</a></div>
  <div class="border border-[hsl(0,0%,26%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊲</a></div>
  <div class="border border-[hsl(0,0%,24%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊳</a></div>
  <div class="border border-[hsl(0,0%,22%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊴</a></div>
  <div class="border border-[hsl(0,0%,20%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊵</a></div>
  <div class="border border-[hsl(0,0%,18%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊶</a></div>
  <div class="border border-[hsl(0,0%,16%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊷</a></div>
  <div class="border border-[hsl(0,0%,14%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊸</a></div>
  <div class="border border-[hsl(0,0%,12%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊹</a></div>
  <div class="border border-[hsl(0,0%,10%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊺</a></div>
  <div class="border border-[hsl(0,0%,8%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊻</a></div>
  <div class="border border-[hsl(0,0%,6%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊼</a></div>
  <div class="border border-[hsl(0,0%,4%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊽</a></div>
  <div class="border border-[hsl(0,0%,2%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊾</a></div>
  <div class="border border-[hsl(0,0%,0%)] cursor-pointer hover:opacity-30 text-[hsl(350,100%,88%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">㊿</a></div>
</div>
-->
<!--
<div class="grid grid-cols-[repeat(51,minmax(0,1fr))] w-full h-6 gap-2 p-4 hubot-sans  text-[22px]">
  <div class="bg-[hsl(0,0%,0%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">75</a></div>
  <div class="bg-[hsl(0,0%,2%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">76</a></div>
  <div class="bg-[hsl(0,0%,4%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">77</a></div>
  <div class="bg-[hsl(0,0%,6%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">78</a></div>
  <div class="bg-[hsl(0,0%,8%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">79</a></div>
  <div class="bg-[hsl(0,0%,10%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">80</a></div>
  <div class="bg-[hsl(0,0%,12%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">81</a></div>
  <div class="bg-[hsl(0,0%,14%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">82</a></div>
  <div class="bg-[hsl(0,0%,16%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">83</a></div>
  <div class="bg-[hsl(0,0%,18%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">84</a></div>
  <div class="bg-[hsl(0,0%,20%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">85</a></div>
  <div class="bg-[hsl(0,0%,22%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">86</a></div>
  <div class="bg-[hsl(0,0%,24%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">87</a></div>
  <div class="bg-[hsl(0,0%,26%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">88</a></div>
  <div class="bg-[hsl(0,0%,28%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">89</a></div>
  <div class="bg-[hsl(0,0%,30%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">90</a></div>
  <div class="bg-[hsl(0,0%,32%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">91</a></div>
  <div class="bg-[hsl(0,0%,34%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">92</a></div>
  <div class="bg-[hsl(0,0%,36%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">93</a></div>
  <div class="bg-[hsl(0,0%,38%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">94</a></div>
  <div class="bg-[hsl(0,0%,40%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">95</a></div>
  <div class="bg-[hsl(0,0%,42%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">96</a></div>
  <div class="bg-[hsl(0,0%,44%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">97</a></div>
  <div class="bg-[hsl(0,0%,46%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">98</a></div>
  <div class="bg-[hsl(0,0%,48%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=rblt2EtFfC4" class="block w-full h-full" target="_blank" rel="noopener noreferrer">99</a></div>

  <div class="bg-[hsl(0,0%,50%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,100%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">0</a></div>
  <div class="bg-[hsl(0,0%,50%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">1</a></div>
  <div class="bg-[hsl(0,0%,52%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">2</a></div>
  <div class="bg-[hsl(0,0%,54%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">3</a></div>
  <div class="bg-[hsl(0,0%,56%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">4</a></div>
  <div class="bg-[hsl(0,0%,58%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">5</a></div>
  <div class="bg-[hsl(0,0%,60%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">6</a></div>
  <div class="bg-[hsl(0,0%,62%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">7</a></div>
  <div class="bg-[hsl(0,0%,64%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">8</a></div>
  <div class="bg-[hsl(0,0%,68%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">9</a></div>
  <div class="bg-[hsl(0,0%,70%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">10</a></div>
  <div class="bg-[hsl(0,0%,72%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">11</a></div>
  <div class="bg-[hsl(0,0%,74%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">12</a></div>
  <div class="bg-[hsl(0,0%,76%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">13</a></div>
  <div class="bg-[hsl(0,0%,78%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">14</a></div>
  <div class="bg-[hsl(0,0%,80%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">15</a></div>
  <div class="bg-[hsl(0,0%,82%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">16</a></div>
  <div class="bg-[hsl(0,0%,84%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">17</a></div>
  <div class="bg-[hsl(0,0%,86%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">18</a></div>
  <div class="bg-[hsl(0,0%,88%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">19</a></div>
  <div class="bg-[hsl(0,0%,90%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">20</a></div>
  <div class="bg-[hsl(0,0%,92%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">21</a></div>
  <div class="bg-[hsl(0,0%,94%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">22</a></div>
  <div class="bg-[hsl(0,0%,96%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">23</a></div>
  <div class="bg-[hsl(0,0%,98%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">24</a></div>
  <div class="bg-[hsl(0,0%,100%)] cursor-pointer hover:opacity-30 text-[hsl(0,0%,0%)] text-center" ><a href="https://www.youtube.com/watch?v=UPUVyDxyfJY" class="block w-full h-full" target="_blank" rel="noopener noreferrer">25</a></div>
</div>
-->
</template>
